<a href="https://colab.research.google.com/github/caburu/Design-and-Analysis-of-Experiments/blob/master/coursera-machine-learning/Semana1_AlgebraLinear_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([[1],[2],[3]])
(m,n) = A.shape
dim_A = A.shape
dim_v = v.shape
A_23 = A[1,2]

print(A)
print(v)
print(m,n)
print(dim_A)
print(dim_v)
print(A_23)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1]
 [2]
 [3]]
4 3
(4, 3)
(3, 1)
6
